### ISSUE TITLE
uninitialized constant Fluent::Clock

### ISSUE THREAD

**Issue by newallone** [tagomoris/fluent-plugin-flowcounter#21]
```
2017-11-16 16:22:45 +0900 [error]: unexpected error error_class=NameError error="uninitialized constant Fluent::Clock"
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-flowcounter-1.1.0/lib/fluent/plugin/out_flowcounter.rb:70:in `block in configure'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-flowcounter-1.1.0/lib/fluent/plugin/out_flowcounter.rb:82:in `start'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:138:in `block in start'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:127:in `block (2 levels) in lifecycle'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:126:in `each'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:126:in `block in lifecycle'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:113:in `each'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:113:in `lifecycle'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/root_agent.rb:137:in `start'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/engine.rb:208:in `start'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/engine.rb:171:in `run'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/supervisor.rb:725:in `run_engine'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/supervisor.rb:478:in `block in run_worker'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/supervisor.rb:650:in `main_process'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/supervisor.rb:473:in `run_worker'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/lib/fluent/command/fluentd.rb:288:in `<top (required)>'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-0.14.11/bin/fluentd:5:in `<top (required)>'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/bin/fluentd:22:in `load'
  2017-11-16 16:22:45 +0900 [error]: /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
  2017-11-16 16:22:45 +0900 [error]: /usr/sbin/td-agent:7:in `load'
  2017-11-16 16:22:45 +0900 [error]: /usr/sbin/td-agent:7:in `<main>'
2017-11-16 16:22:45 +0900 [error]: unexpected error error_class=NameError error="uninitialized constant Fluent::Clock"
  2017-11-16 16:22:45 +0900 [error]: suppressed same stacktrace

...

2017-11-16 16:22:47 +0900 [info]: starting fluentd-0.14.11
```

**Comment by tagomoris** [comment]
Oops. That was introduced in v1.1.0. I fixed at master branch, and released v1.1.1.
Thank you for reporting!
